language: c
os: windows

jobs:
  include:
#    - os: windows
#      install: choco install mingw
#      script: 
#        - cd src
#        - cp ../sys/winnt/Makefile.gcc .
#        - mingw32-make -f Makefile.gcc
    - os: windows
      install: choco install visualstudio2017buildtools
#      install: choco install visualstudio2017-workload-vctools
      language: sh
      script:
        - export
        - export MSVER=14.16.27023
#       - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86
        - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/VC/Tools/MSVC/$MSVER/bin/HostX64/x86
        - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/VC/Tools/MSVC/$MSVER/bin/HostX64/x64
        - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/Common7/IDE/VC/VCPackages
        - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/Common7/IDE/CommonExtensions/Microsoft/TestWindow
        - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/MSBuild/Current/bin/Roslyn
        - export
        - cd src
        - cp ../sys/winnt/Makefile.msc ./Makefile
        - nmake install

#        - find . -name 'fixes36.3' -print
#        - find . -name 'fixes36.3' -print
#        - find /c -name 'mspdbcore.dll' -print
#        - ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86
#        - /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x64/nmake.exe install
#        - export PATH=$PATH:/c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/VC/Tools/MSVC/14.16.27023/bin/Hostx64/x86
#        - export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin"
#        - ls /c
#        - ls /c/Program\ Files
#        - ls /c/Program\ Files\ \(x86\)
#        - ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio
#        - find /c -name 'mspdbcore.dll' -print
#        - ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017
#        - ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community
#        - ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC
#        - ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools
#        - ls /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/Community/VC/Tools/MSVC
#
#        - "%(x86)%/Microsoft Visual Studio/2017/Community/VC/Auxiliary/Build/vcvarsamd64_x86.bat"
#
#
#    - env: 
#      language: sh
#      before_install:
#
#script: "cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../ && QT_SELECT=5 make MOC=moc install"
#
#matrix:
#  include:
#    - env: HINTS=linux
#      compiler: gcc
#    - env: HINTS=linux
#      compiler: clang
#    - env: HINTS=linux-x11
#      compiler: gcc
#    - env: HINTS=linux-qt5
#      compiler: gcc
#      addons:
#        apt:
#          packages:
#            - qtbase5-dev
#            - qtmultimedia5-dev
#            - qtbase5-dev-tools
#    - env: HINTS=linux-minimal
#      compiler: gcc
#      script: |
#              cd sys/unix/ && sh setup.sh hints/$HINTS && cd ../../
#              sed -i '/^#define CLIPPING/d'       include/config.h
#              sed -i '/^#define COMPRESS/d'       include/config.h
#              #sed -i '/^#define DOAGAIN/d'        include/config.h
#              sed -i '/^#define DUMPLOG/d'        include/config.h
#              #sed -i '/^#define GDBPATH/d'        include/config.h
#              #sed -i '/^#define GREPPATH/d'       include/config.h
#              sed -i '/^#define INSURANCE/d'      include/config.h
#              sed -i '/^#define LOGFILE/d'        include/config.h
#              sed -i '/^#define NEWS/d'           include/config.h
#              sed -i '/^#define PANICLOG/d'       include/config.h
#              #sed -i '/^#define STATUS_HILITES/d' include/config.h
#              sed -i '/^#define SYSCF/d'          include/config.h
#              sed -i '/^#define USER_SOUNDS/d'    include/config.h
#              sed -i '/^#define XLOGFILE/d'       include/config.h
#
#              sed -i '/^#define MAIL/d'           include/unixconf.h
#              sed -i '/^#define SHELL/d'          include/unixconf.h
#              sed -i '/^#define SUSPEND/d'        include/unixconf.h
#              sed -i 's/^#define TEXTCOLOR//'     include/unixconf.h
#              make install
#              cat dat/options
#
#sudo: false
#
#notifications:
#  email:
#    recipients:
#      - devteam@nethack.org
#
